included:
  - practice/HIGPractice/HIGPractice

excluded:
  - practice/HIGPractice/HIGPractice.xcodeproj
  - practice/HIGPractice/HIGPracticeTests
  - practice/HIGPractice/HIGPracticeUITests

disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - closure_spacing
  - operator_usage_whitespace
  - explicit_init
  - yoda_condition

reporter: "xcode"
