name: 학습 챕터 템플릿
description: Phase/Framework/Day 단위 학습 이슈를 생성합니다.
title: "[학습] Phase X - Framework - Day Y"
labels: ["learning", "chapter"]
body:
  - type: dropdown
    id: phase
    attributes:
      label: 학습 Phase
      options:
        - Phase 1: App Frameworks
        - Phase 2: App Services
        - Phase 3: Graphics & Media
        - Phase 4: System & Network
        - Phase 5: iOS 26
    validations:
      required: true

  - type: input
    id: framework
    attributes:
      label: Framework 이름
      placeholder: 예) SwiftUI
    validations:
      required: true

  - type: input
    id: chapter
    attributes:
      label: Day/Chapter
      placeholder: 예) Day 1
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: 오늘 학습 목표
      description: 이번 이슈에서 완료할 학습 목표를 작성하세요.
      placeholder: |
        - 핵심 개념 3개 이해
        - 튜토리얼 1개 실습 완료
        - 샘플 코드 비교 포인트 3개 정리
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 체크리스트
      value: |
        - [ ] 실습 코드 구현
        - [ ] 로컬 빌드/테스트 확인
        - [ ] PR 생성 및 CI 확인
        - [ ] 머지 후 Velog 회고 작성
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: 완료 조건 (Definition of Done)
      placeholder: |
        - 목표 기능 동작 확인
        - 필수 CI 통과
        - 회고 링크 기록 완료
    validations:
      required: true
