name: 학습 템플릿
description: Phase/Framework 단위 학습 이슈를 생성합니다.
title: "[학습] Phase X - Framework"
labels: ["learning"]
body:
  - type: dropdown
    id: phase
    attributes:
      label: 학습 Phase
      options:
        - Phase 1: App Frameworks
        - Phase 2: App Services
        - Phase 3: Graphics & Media
        - Phase 4: System & Network
        - Phase 5: iOS 26
    validations:
      required: true

  - type: input
    id: framework
    attributes:
      label: Framework 이름
      placeholder: 예) WidgetKit
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: 이번 학습 목표
      placeholder: |
        - 핵심 개념 3개 이해
        - 튜토리얼 실습 완료
        - 샘플 구조 비교 포인트 정리
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 체크리스트
      value: |
        - [ ] site 개념 확인
        - [ ] tutorials 실습
        - [ ] samples 구조 비교
        - [ ] PR 생성 및 CI 확인
        - [ ] 머지 후 LEARNING_LOG/Velog 기록
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: 완료 조건 (Definition of Done)
      placeholder: |
        - 목표 기능 동작 확인
        - 필수 CI 통과
        - 회고 링크 기록 완료
    validations:
      required: true
