name: Learning Chapter
about: Track one learning chapter from implementation to retrospective
title: "[Chapter] Phase X - Framework - Chapter Y"
labels: ["chapter", "learning"]
body:
  - type: dropdown
    id: phase
    attributes:
      label: Phase
      options:
        - Phase 1: App Frameworks
        - Phase 2: App Services
        - Phase 3: Graphics & Media
        - Phase 4: System & Network
        - Phase 5: iOS 26
    validations:
      required: true

  - type: input
    id: framework
    attributes:
      label: Framework
      placeholder: e.g. SwiftUI
    validations:
      required: true

  - type: input
    id: chapter
    attributes:
      label: Chapter
      placeholder: e.g. Chapter 1
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Learning Goals
      description: What will be completed in this chapter?
      placeholder: |
        - Build ...
        - Understand ...
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Task Checklist
      value: |
        - [ ] Implement chapter code
        - [ ] Run build/test checks
        - [ ] Open PR and request review
        - [ ] Merge and write Velog retrospective
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      placeholder: |
        - UI works as intended
        - CI passes
        - Retrospective link added
    validations:
      required: true
